/// Provides a Dio interceptor for logging HTTP request and response details.
///
/// This library contains [DioInterceptor], which can be added to a Dio instance
/// to automatically log information about outgoing requests, successful responses,
/// and errors.
library;

import 'package:dio/dio.dart';
import 'package:logger/logger.dart'; // Assuming 'logger' package is used
import 'network_logging.dart';

/// Header names whose values are secrets and must never be logged verbatim.
const _sensitiveHeaders = <String>{
  'authorization',
  'cookie',
  'set-cookie',
  'x-api-key',
  'proxy-authorization',
};

/// Returns the header value, or `<redacted>` for sensitive headers so tokens
/// and cookies don't leak into logs.
String redactedHeaderValue(String key, Object? value) =>
    _sensitiveHeaders.contains(key.toLowerCase()) ? '<redacted>' : '$value';

/// Payload metadata only: truncation cannot sanitize arbitrary credentials.
String _bodySummary(Object? data) {
  if (data is Map) return '<map: ${data.length} entries; values omitted>';
  if (data is List) return '<list: ${data.length} items; values omitted>';
  if (data is FormData) {
    return '<multipart: ${data.fields.length} fields, ${data.files.length} files; values omitted>';
  }
  return '<payload omitted>';
}

/// A [Dio] interceptor that logs HTTP requests, responses, and errors.
///
/// This interceptor can be useful for debugging network interactions during development.
/// It uses an instance of [Logger] (from the `logger` package or a similar one)
/// to output log messages. Logging can be enabled or disabled via the [enableLogging] flag.
///
/// ### Usage:
/// ```dart
/// final dio = Dio();
/// final logger = Logger(); // Your logger instance
///
/// dio.interceptors.add(DioLoggingInterceptor( // Renamed for clarity from original DioInterceptor
///   logger: logger,
///   enableLogging: true, // Default is true
/// ));
/// ```
class DioLoggingInterceptor extends Interceptor {
  // Renamed class for clarity
  /// The [Logger] instance used for outputting log messages.
  /// If null, no logging will occur even if [enableLogging] is true.
  final Logger? logger;

  /// A flag to enable or disable logging.
  /// Defaults to `true`. If `false`, no logs will be generated by this interceptor.
  final bool enableLogging;

  /// Creates a [DioLoggingInterceptor].
  ///
  /// - [logger]: The [Logger] instance to use.
  /// - [enableLogging]: Whether logging is enabled. Defaults to `true`.
  DioLoggingInterceptor({
    this.logger,
    this.enableLogging = true,
  });

  /// Called when a request is about to be sent.
  ///
  /// Logs metadata only; URIs, headers and contents may contain credentials.
  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    if (enableLogging && logger != null) {
      final logMessage = StringBuffer();
      logMessage.writeln('--- Dio Request ---');
      logMessage.writeln('Method: ${options.method}');
      logMessage.writeln('URI: <omitted>');
      if (options.headers.isNotEmpty) {
        logMessage
            .writeln('Headers: <${options.headers.length} entries; omitted>');
      }
      if (options.data != null) {
        logMessage.writeln('Data: ${_bodySummary(options.data)}');
      }
      logMessage.write('-------------------');
      logNetworkMetadata(logger, Level.info, logMessage.toString());
    }
    super.onRequest(options, handler); // Ensure to call super or handler.next()
  }

  /// Called when a response is received.
  ///
  /// Logs status code and payload metadata, not server-controlled text.
  @override
  void onResponse(Response response, ResponseInterceptorHandler handler) {
    if (enableLogging && logger != null) {
      final logMessage = StringBuffer();
      logMessage.writeln('--- Dio Response ---');
      logMessage.writeln('URI: <omitted>');
      logMessage.writeln('Status Code: ${response.statusCode}');

      if (response.data != null) {
        logMessage.writeln('Data: ${_bodySummary(response.data)}');
      }
      logMessage.write('--------------------');
      logNetworkMetadata(logger, Level.info, logMessage.toString());
    }
    super.onResponse(
        response, handler); // Ensure to call super or handler.next()
  }

  /// Called when an error occurs during a request or response.
  ///
  /// Logs error type, status and payload metadata, never raw exception details.
  @override
  void onError(DioException err, ErrorInterceptorHandler handler) {
    if (enableLogging && logger != null) {
      final logMessage = StringBuffer();
      logMessage.writeln('--- Dio Error ---');
      logMessage.writeln('URI: <omitted>');
      logMessage.writeln('Error Type: ${err.type}');

      if (err.response != null) {
        logMessage.writeln('Status Code: ${err.response!.statusCode}');

        if (err.response!.data != null) {
          logMessage
              .writeln('Response Data: ${_bodySummary(err.response!.data)}');
        }
      }
      logMessage.write('-----------------');
      logNetworkMetadata(logger, Level.error, logMessage.toString());
    }
    super.onError(err, handler); // Ensure to call super or handler.next()
  }
}
